services:
  - type: web
    name: mousenet-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: YOOMONEY_RECEIVER
        sync: false
      - key: YOOMONEY_REDIRECT_URI
        sync: false
      - key: YOOMONEY_NOTIFICATION_SECRET
        sync: false
